const CONFIG = {
  env: 'development',
  TAB_CRUISE_URL: 'http://cruises.united.com/?cm_mmc=Link-_-UAL-Site_Referral-_-20150925-HP_SW-_-Generic_HP',
  TAB_VACATION_URL: '/web/en-US/apps/vendors/out.aspx?i=vacationstab',
  BAG_RULES_URL: '/CMS/en-US/travel/Pages/ChangedBagRulesOptionalServices.aspx?v_ctrk=BTWIL$0-1850-5763-1-3890&int_source=brnd&int_medium=uacom2&int_campaign=IPOS_Bk_Trvl_Wdgt_link_alm12724&targeting=US_EN&asset_position=BTWIL&launch_date=2013-11-07',
  OPT_SVC_URL: '/CMS/en-US/travel/Pages/ChangedBagRulesOptionalServices.aspx?v_ctrk=BTWIL$0-1850-5763-1-3890&int_source=brnd&int_medium=uacom2&int_campaign=IPOS_Bk_Trvl_Wdgt_link_alm12724&targeting=US_EN&asset_position=BTWIL&launch_date=2013-11-07#optionalServices',
  API_CAR_LOCATION_REQUEST_URL: 'https://www.rentalcars.com/FTSAutocomplete.do?solrIndex=fts_en&solrRows=10&solrTerm=',
  ADVANCED_FLIGHT_SEARCH_URL: '/ual/en/us/flight-search/book-a-flight',
  FIND_FLIGHTS_URL: '/ual/en/us/flight-search/book-a-flight/results/',
  FIND_HOTELS_URL: 'https://hotels.united.com/search.do?locale=en_US&POS=UNITED_US',
  FIND_CARS_URL: 'https://united-uat.rentalcars.com/LoadingSearchResults.do?emptySearchResults=true',
  FIND_CARS_URL_BASE: 'united-uat.rentalcars.com',
  VIEW_ACCOUNT: '/web/en-US/apps/mileageplus/statement/recentActivity.aspx?MobileOff=1',
  PLATYPUS_BASE_URL: 'https://qa1.united.com',
  UAL_BASE_URL: 'https://integration.united.com',
  CONTACT: '/web/en-US/content/Contact/default.aspx',
  SEARCH: '/web/en-US/apps/search/default.aspx',
  RESERVATIONS: '/web/en-US/content/reservations/default.aspx',
  DEALS: '/web/en-US/content/deals/default.aspx',
  TRAVEL: '/web/en-US/content/travel/default.aspx',
  MILEAGE: '/web/en-US/content/mileageplus/default.aspx',
  MY_ACCOUNT: '/web/en-US/apps/account/account.aspx?POS=US&MobileOff=1',
  TIME_TABLE_RESULTS: '/web/en-US/apps/travel/timetable/default.aspx?OF=1&MobileOff=1&',
  FLIGHT_CHECKIN_URL: '/travel/checkin/quickstart.aspx?MobileOff=1',
  CHECKIN_WITH_MP_NUMBER_URL: '/travel/checkin/start.aspx?LangCode=en-US&MobileOff=1',
  CHECKIN_PROCESSING_URL: '/web/en-US/Content/travel/airport/process/default.aspx?MobileOff=1',
  DOWNLOAD_APP_LINK: '/web/en-US/content/travel/wireless/default.aspx',
  MYTRIPS_RESERVATION_URL: '/web/en-US/apps/reservation/default.aspx?MobileOff=1',
  MYTRIPS_FORM_SUBMIT_URL: '/ual/en/us/mytrips/trips/getflightreservationbyname',
  UPGRADE_LIST_URL: '/web/en-US/apps/travel/flightstatus/default.aspx',
  PREVIOUS_FLIGHT_STATUS_URL: '/web/en-US/apps/travel/flightstatus/default.aspx?',
  FLIGHT_SEATS_URL: '/ual/en/us/mytrips/trips/flightseats',
  FLIGHT_MANAGE_URL: '/ual/en/us/mytrips/trips/flightmanage',
  STAR_ALLIANCE_URL: '/web/en-US/content/company/alliance/star.aspx',
  ENSIGHTEN_BOOTSTRAP: 'https://nexus.ensighten.com/united/UnitedStage_v3/Bootstrap.js',
  COOKIE_DOMAIN: 'localhost',
};

export default CONFIG;
