/*
 * BookFlightContainer constants
 */

export const BOOK_FLIGHT_ORIGIN_LOCATION_SELECTED = 'unitedapp/App/BOOK_FLIGHT_ORIGIN_LOCATION_SELECTED';
export const BOOK_FLIGHT_DESTINATION_LOCATION_SELECTED = 'unitedapp/App/BOOK_FLIGHT_DESTINATION_LOCATION_SELECTED';
export const CORPORATE_BOOK_CHECKED = 'unitedapp/App/CORPORATE_BOOK_CHECKED';
export const NONSTOP_CHECKED = 'unitedapp/App/NONSTOP_CHECKED';
export const FLEXIBLE_DATES_CHECKED = 'unitedapp/App/FLEXIBLE_DATES_CHECKED';
export const ROUNDTRIP_CHECKED = 'unitedapp/App/ROUNDTRIP_CHECKED';
export const SET_ORIGIN_CODE = 'unitedapp/App/SET_ORIGIN_CODE';
export const SET_DESTINATION_CODE = 'unitedapp/App/SET_DESTINATION_CODE';
export const DISABLE_TRAVELER_BUTTONS = 'unitedapp/App/DISABLE_TRAVELER_BUTTONS';
export const UPDATE_PASSENGER_INFO = 'unitedapp/App/UPDATE_PASSENGER_INFO';
export const OPEN_OR_CLOSE_PASSENGER_MENU = 'unitedapp/App/OPEN_OR_CLOSE_PASSENGER_MENU';
export const UPDATE_FULL_PASSENGERS = 'unitedapp/App/UPDATE_FULL_PASSENGERS';
