
/*
 * FlightStatusContainer constants
 */

export const DATE_SELECTED = 'unitedapp/App/DATE_SELECTED';
export const FLIGHT_SELECTED = 'unitedapp/App/FLIGHT_SELECTED';
export const SET_FLIGHT_STATUS_ORIGIN_CODE = 'unitedapp/App/SET_FLIGHT_STATUS_ORIGIN_CODE';
export const SET_FLIGHT_STATUS_DESTINATION_CODE = 'unitedapp/App/SET_FLIGHT_STATUS_DESTINATION_CODE';
export const FLIGHT_STATUS_ORIGIN_LOCATION_SELECTED = 'unitedapp/App/FLIGHT_STATUS_ORIGIN_LOCATION_SELECTED';
export const FLIGHT_STATUS_DESTINATION_LOCATION_SELECTED = 'unitedapp/App/FLIGHT_STATUS_DESTINATION_LOCATION_SELECTED';
export const UPDATE_FLIGHT_STATUS_DATE = 'unitedapp/App/UPDATE_FLIGHT_STATUS_DATE';
export const FLIGHT_SEGMENT_SELECTED = 'unitedapp/App/FLIGHT_SEGMENT_SELECTED';
